API_VERSION = '/api/v1';
USER_ENDPOINT = API_VERSION + '/users';
LOCATION_ENDPOINT = API_VERSION + '/locations';
IMAGE_ENDPOINT = API_VERSION + '/image';
REVIEW_ENDPOINT = API_VERSION + '/reviews';
NOTI_ENDPOINT = API_VERSION + '/notis';
ROUTING_ENDPOINT = API_VERSION + '/routing';
AUTH_ENDPOINT = API_VERSION + '/auth';

module.exports = {
  USER_ENDPOINT,
  LOCATION_ENDPOINT,
  IMAGE_ENDPOINT,
  REVIEW_ENDPOINT,
  NOTI_ENDPOINT,
  ROUTING_ENDPOINT,
  AUTH_ENDPOINT,
};
